version: "3.7"
services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    environment:
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USER: homestead
      DB_PASSWORD: secret
      ENCRYPTER_KEY: def0000000101d3863b719a539d102fdaf769f11ce514d47c30961727fe1615b7dcca4b9be220c2f1db888eb19937067f5f1d76f3a26b742b7f76d0adeda30e457ca6598
    ports:
        - "8080:8080"
    volumes:
      - ./:/var/www/
    depends_on:
      - temporal

  db:
    image: postgres
    environment:
      POSTGRES_USER: homestead
      POSTGRES_DB: homestead
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup
    ports:
      - "7233:7233"
    volumes:
      - ./docker/temporal:/etc/temporal/config/dynamicconfig

  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web
    ports:
      - "8088:8088"
