version: '2.7'

rpc:
    listen: tcp://127.0.0.1:6001

logs:
    mode: production
    encoding: console
    level: debug

server:
    command: "php app.php"
    relay: pipes

http:
    address: 0.0.0.0:8080
    middleware: [ "headers", "gzip", "websockets", "static", "otel" ]
    headers:
        cors:
            allowed_origin: "*"
            allowed_headers: "*"
            allowed_methods: "GET,POST,PUT,DELETE"
            allow_credentials: true
            exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
            max_age: 600
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
    otel:
        insecure: true
        compress: false
        client: http
        exporter: otlp
        service_name: rr-web
        service_version: 1.0.0
        endpoint: collector:4318

jobs:
    consume: [ ]
    pool:
        num_workers: 2
        supervisor:
            max_worker_memory: 100

temporal:
    address: temporal:7233
    activities:
        num_workers: 5

websockets:
    broker: default
    path: "/ws"

broadcast:
    default:
        driver: redis
        config:
            addrs:
                - redis:6379
